## Analyse de Data

### Problématique
L'impact de jeux vidéo sur la cohérence  familiale (l'objectif de questionnaire)

### chargement de data

In [1]:
import pandas as pd 
df = pd.read_csv("../data/raw/Questionnaire.csv", sep=";",encoding="latin1")

### Compréhension du data

#### Un échantillon de data

In [2]:
df.head(10)

,Âge :,Genre :,Situation familiale :,Nombre d'enfants :,Niveau d'études :,Jouez vous aux jeux vidéo ?,Fréquence de jeu (par semaine) :,Où jouez vous habituellement aux jeux vidéo ? (Sélection multiple possible),Vos enfants jouent ils aux jeux vidéo ?,Fréquence de jeu de vos enfants (par semaine) :,Où vos enfants jouent-ils habituellement aux jeux vidéo ? (Sélection multiple possible),Avez-vous remarqué des changements de comportement chez vous ou vos enfants liés aux jeux vidéo ?,Pensez-vous que les jeux vidéo ont un impact positif ou négatif sur la communication familiale ?,Les jeux vidéo ont-ils influencé le temps passé ensemble en famille ?,Avez-vous des règles spécifiques concernant l'utilisation des jeux vidéo à la maison ?,Pensez-vous que les jeux vidéo peuvent aider à gérer le stress ou l'anxiété ?,Avez-vous des préoccupations concernant l'impact des jeux vidéo sur la santé mentale de vos enfants ?
0,18-24,Homme,Marié(e) / En couple,2,Master (Bac +5),Oui,Moins de 1 heure,"À la maison (salon, chambre, etc.), En ligne a...",Oui,Moins de 1 heure,"Chez des amis / famille, Dans des lieux public...",Oui,Positif,Diminué,Non,Oui,Oui
1,45-54,Homme,Marié(e) / En couple,3,Doctorat (Bac +8),Oui,Moins de 1 heure,En ligne avec des amis,Oui,Moins de 1 heure,En ligne avec des amis,Non,Négatif,Augmenté,Oui,Non,Oui
2,25-34,Femme,Marié(e) / En couple,Aucun,Doctorat (Bac +8),Oui,Moins de 1 heure,"À la maison (salon, chambre, etc.)",Pas d'enfants,Ne sait pas,Autres,Non,Négatif,Diminué,Non,Oui,Pas d'enfants
3,25-34,Femme,Marié(e) / En couple,2,Master (Bac +5),Oui,1-3 heures,En ligne avec des amis,Oui,Moins de 1 heure,"À la maison (salon, chambre, etc.)",Oui,Négatif,Diminué,Oui,Non,Non
4,35-44,Femme,Marié(e) / En couple,2,Master (Bac +5),Non,Moins de 1 heure,"À la maison (salon, chambre, etc.)",Oui,Moins de 1 heure,"À la maison (salon, chambre, etc.)",Oui,Négatif,Diminué,Oui,Non,Non
5,35-44,Femme,Marié(e) / En couple,3,Master (Bac +5),Non,Moins de 1 heure,Autres,Non,Moins de 1 heure,Autres,Non,Négatif,Diminué,Non,Non,Oui
6,45-54,Homme,Marié(e) / En couple,4 et plus,Master (Bac +5),Non,Moins de 1 heure,Autres,Non,Ne sait pas,Autres,Non,Négatif,Pas de changement,Non,Non,Oui
7,35-44,Femme,Marié(e) / En couple,2,Licence (Bac +3/+4),Non,Moins de 1 heure,"À la maison (salon, chambre, etc.)",Oui,1-3 heures,"À la maison (salon, chambre, etc.)",Oui,Négatif,Diminué,Oui,Non,Oui
8,45-54,Homme,Marié(e) / En couple,4 et plus,Master (Bac +5),Non,Moins de 1 heure,Autres,Oui,1-3 heures,"À la maison (salon, chambre, etc.)",Oui,Négatif,Diminué,Oui,Non,Oui
9,25-34,Homme,Célibataire,Aucun,Doctorat (Bac +8),Oui,Moins de 1 heure,En ligne avec des amis,Pas d'enfants,Ne sait pas,Autres,Non,Négatif,Diminué,Non,Non,Pas d'enfants

### Métadonnée de data

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 17 columns):
 #   Column                                                                                                     Non-Null Count  Dtype
---  ------                                                                                                     --------------  -----
 0     Âge :                                                                                                    90 non-null     str
 1     Genre :                                                                                                  90 non-null     str
 2     Situation familiale :                                                                                    90 non-null     str
 3     Nombre d'enfants :                                                                                       90 non-null     str
 4     Niveau d'études :                                                                                        90 non-null     str
 5     Jouez vous aux jeux vidéo ?                                                                              90 non-null     str
 6     Fréquence de jeu (par semaine) :                                                                         89 non-null     str
 7   Où jouez vous habituellement aux jeux vidéo ? (Sélection multiple possible)                                90 non-null     str
 8     Vos enfants jouent ils aux jeux vidéo ?                                                                  90 non-null     str
 9     Fréquence de jeu de vos enfants (par semaine) :                                                          60 non-null     str
 10  Où vos enfants jouent-ils habituellement aux jeux vidéo ? (Sélection multiple possible)                    61 non-null     str
 11    Avez-vous remarqué des changements de comportement chez vous ou vos enfants liés aux jeux vidéo ?        90 non-null     str
 12    Pensez-vous que les jeux vidéo ont un impact positif ou négatif sur la communication familiale ?         90 non-null     str
 13    Les jeux vidéo ont-ils influencé le temps passé ensemble en famille ?                                    90 non-null     str
 14    Avez-vous des règles spécifiques concernant l'utilisation des jeux vidéo à la maison ?                   90 non-null     str
 15    Pensez-vous que les jeux vidéo peuvent aider à gérer le stress ou l'anxiété ?                            90 non-null     str
 16    Avez-vous des préoccupations concernant l'impact des jeux vidéo sur la santé mentale de vos enfants ?    90 non-null     str
dtypes: str(17)
memory usage: 12.1 KB

#### Récapulatif statistique

In [4]:
df.describe()

,Âge :,Genre :,Situation familiale :,Nombre d'enfants :,Niveau d'études :,Jouez vous aux jeux vidéo ?,Fréquence de jeu (par semaine) :,Où jouez vous habituellement aux jeux vidéo ? (Sélection multiple possible),Vos enfants jouent ils aux jeux vidéo ?,Fréquence de jeu de vos enfants (par semaine) :,Où vos enfants jouent-ils habituellement aux jeux vidéo ? (Sélection multiple possible),Avez-vous remarqué des changements de comportement chez vous ou vos enfants liés aux jeux vidéo ?,Pensez-vous que les jeux vidéo ont un impact positif ou négatif sur la communication familiale ?,Les jeux vidéo ont-ils influencé le temps passé ensemble en famille ?,Avez-vous des règles spécifiques concernant l'utilisation des jeux vidéo à la maison ?,Pensez-vous que les jeux vidéo peuvent aider à gérer le stress ou l'anxiété ?,Avez-vous des préoccupations concernant l'impact des jeux vidéo sur la santé mentale de vos enfants ?
count,90,90,90,90,90,90,89,90,90,60,61,90,90,90,90,90,90
unique,5,2,2,5,6,2,5,13,3,5,11,2,3,3,2,3,3
top,18-24,Homme,Célibataire,Aucun,Master (Bac +5),Oui,Moins de 1 heure,"À la maison (salon, chambre, etc.)",Pas d'enfants,jamais jouer,jamais jouer,Non,Négatif,Diminué,Non,Non,Pas d'enfants
freq,39,46,50,55,28,55,42,35,52,19,19,51,57,54,58,40,41

#### Analyse de la qualité des données
##### pour cela je developpe un  script devra être capable de détecter les anomalies automatiquement :

##### # Configuration du chemin du projet (Project Root)

In [5]:

import sys
from pathlib import Path

# Dossier racine du projet
PROJECT_ROOT = Path().resolve().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

print(PROJECT_ROOT)
print(sys.path[:3])

/home/reda/medical-questionnaire-ml
['/home/reda/medical-questionnaire-ml', '/usr/lib/python312.zip', '/usr/lib/python3.12']

##### # Rapport synthétique

In [6]:
from ml.anomaly_detection import AnomalyDetector
detector = AnomalyDetector(df)
detector.run()

=================================================================
             RAPPORT DE DÉTECTION DES ANOMALIES
=================================================================

Informations générales
-----------------------------------------------------------------
Nombre d'observations : 90
Nombre de variables   : 17

Qualité des données
-----------------------------------------------------------------
Doublons               : 0
Colonnes constantes    : 0
Variables catégorielles: 17
Variables numériques   : 0

Valeurs manquantes
-----------------------------------------------------------------
Colonnes concernées : 3

  Fréquence de jeu (par semaine) :                   1 (1.1 %)
  Fréquence de jeu de vos enfants (par semaine) :    30 (33.3 %)
Où vos enfants jouent-ils habituellement aux jeux vidéo ? (Sélection multiple possible)    29 (32.2 %)

Conclusion
-----------------------------------------------------------------
Le jeu de données présente une bonne qualité globale.
Les principales anomalies concernent les valeurs manquantes.
Le dataset est prêt pour l'étape de nettoyage.
=================================================================

### Conclusions de l'analyse :
#### À l'issue de l'analyse exploratoire, plusieurs constats ont été établis :
- certaines variables ne sont pas standardisées et nécessitent une harmonisation 
- certaines colonnes contiennent des données sous des formats hétérogènes (catégoriels et numériques), ce qui nécessitera un prétraitement adapté avant leur exploitation.

### Décision

Ces observations montrent que le jeu de données nécessite une étape de prétraitement avant toute modélisation. La prochaine phase consistera à standardiser les variables, traiter les valeurs manquantes et préparer les données pour les algorithmes de Machine Learning.